### ISSUE TITLE
Testing the Game

### ISSUE THREAD

**Issue by dustingraham** [JohnnyTurbo/TBT_Game#1]
Hello,

I saw you link to this repo from: https://www.youtube.com/watch?v=b9-LKprJht0

I was interested to see how you handled some of the things such as highlighting the grid for the available targets. I downloaded this development branch, but I opened each scene and none of the scenes looked like the youtube video.

I also couldn't figure out a way to test it. I ripped out the alpha prevention, but it still required login and I didn't want to try to rip out the login.

Wondering if you could advise how to quickly get into play mode similar to the 6:22 mark of the youtube video where you demonstrated clicking on the tiles, enemies, allies, moving, targeting, etc.

Thanks for sharing the code.
-Dustin

**Comment by dustingraham** [comment]
Figured it out -- you swap out the material. :) That's the main thing I was curious about, so all good now. I'll leave this for you to close out. No worries if you don't want to make any changes. Appreciate the video and repo.

**Comment by JohnnyTurbo** [comment]
Glad you figured that out! The game has evolved a lot since I made that video, mostly to make it more mobile friendly and unfortunately, it would probably be quite difficult to get it up and running as it involves quite a bit of custom PHP code and communication with a MySQL database. Nonetheless, I'm happy you are finding use from my code, feel free to ask me any other questions 😃
